version: "3.8"

services:
  db:
    image: mysql:8.4
    container_name: mysql_db_a3
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: salesdb
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
    ports:
      - "3309:3306"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql-data:/var/lib/mysql
    networks:
      - sales-network

  api-main:
    build:
      context: ./api-main
    container_name: api-main-a3
    restart: always
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      DB_HOST: db
      DB_USER: mysql
      DB_PASSWORD: mysql
      DB_NAME: salesdb
      DB_PORT: 3306
    depends_on:
      - db
    networks:
      - sales-network

  api-report:
    build:
      context: ./api-report
    container_name: api-report-a3
    restart: always
    ports:
      - "3001:3001"
    environment:
      PORT: 3001
      DB_HOST: db
      DB_USER: mysql
      DB_PASSWORD: mysql
      DB_NAME: salesdb
      DB_DIALECT: mysql
      DB_PORT: 3306
    depends_on:
      - db
    networks:
      - sales-network

volumes:
  mysql-data:

networks:
  sales-network:
    driver: bridge
